name: 'eligible-actor'
description: 'Execute a GitHub Action only if the (triggering) actor is eligible (=authorised) to do so.'
author: 'Stefan Natter (https://natterstefan.me)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'sliders'
  color: 'green'
inputs:
  ruleId:
    required: true
    description: 'Id of the rule to apply.'
  rulesFile:
    required: false
    description: 'Name to the file containing the rules. It must be located in ./github!'
    default: 'eligible-actors-rules.json'
